get http://localhost:3000/

###

post http://localhost:3000/regate/login
Content-Type: application/json

{
    "email": "John@gmail.com",
    "password": "johndoe"
}

###

post http://localhost:3000/regate/register
Content-Type: application/json

{
    "fullName": "John Doe",
    "email": "Johssn@gmail.com",
    "password": "johndoe"
}

###

get http://localhost:3000/regate/user/viewUser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyUGF5bG9hZCI6eyJlbWFpbCI6IkpvaG5AZ21haWwuY29tIn0sImlhdCI6MTYyNzkxMzMwNH0.b4ZigVZxKo3MUMZa8m8BzkYxwsvf9MeDO1rRGVXjDX0

{
    "id": "6106aa7c5ed6301bed78bc18"
}

###

get https://research-gate.herokuapp.com/regate/user/viewUser
Content-Type: application/json

{
    "id": "60f3e6881f736723ca49bab7"
}